name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
					check-latest: true
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
